[package]
name = "udarnik"
version = "0.1.0"
authors = ["Ding Xiang Fei <dingxiangfei2009@gmail.com>"]
edition = "2018"

[dependencies]
aead = "0.2.0"
aes-gcm-siv = "0.3.0"
bitvec = "0.16.0"
crossbeam = "0.7.0"
curve25519-dalek = "2"
derive_more = "0.15.0"
dyn-clone = "1.0"
failure = "0.1.5"
futures = "0.3.0"
generic-array = "0.12"
lazy_static = "1"
lru = "0.4.0"
log = "0.4.0"
rand = "0.7.2"
rand_chacha = "0.2.1"
rayon = "1.2.0"
sha3 = "0.8.1"

[dependencies.async-std]
version = "1.0"
features = ["attributes"]

[dependencies.tokio]
version = "0.2.0"
features = ["macros", "io-driver", "time", "rt-threaded"]

[dependencies.sss]
git = "https://github.com/dingxiangfei2009/sss"
rev = "f4f30e61d0d2616327f7adbf7e77e53040830e8f"
